### PR TITLE
Update to density 0.14.1

### PR DESCRIPTION
**Pull request by gpnuma**

### CODE REVIEW

**Comment by gpnuma** [comment]
There is a problem with the decompress work buffer size for density in lzbench.
I'll fix it and update this PR in the forthcoming days.

**Comment by gpnuma** [comment]
I'll reopen this when I can get some time to check lzbench work buffer sizes

**Comment by inikep** [comment]
Do you need additional work buffer (that is not an input or output buffer)?
Look at `lzbench_brieflz_init` in https://github.com/inikep/lzbench/blob/master/_lzbench/compressors.cpp

**Comment by gpnuma** [comment]
Thanks @inikep I'll check this out. As soon as all the tests are passing properly I'll reopen the PR, I also have an issue to open regarding a question on the timings performed which I'll do now.

**Pull request closed without merging**
