### PR TITLE
Add libdeflate

### PR DESCRIPTION
**Pull request by jibsen**
This adds [libdeflate](https://github.com/ebiggers/libdeflate).

### CODE REVIEW

**Comment by inikep** [comment]
Thanks Jørgen

**Comment by jibsen** [comment]
It's failing to compile on MacOS on Travis -- apparently they have a `heapsort` function in `stdlib.h`. Adding `_POSIX_C_SOURCE` broke snappy (which uses `ssize_t` without including the proper header). I don't know much about MacOS, so perhaps you are in a better position to fix this?

Alternatively, @ebiggers might be willing to fix it upstream for MacOS compatibility.

**Comment by inikep** [comment]
I see in logs it's failing with snappy. I think Travis updated MacOS VM.

**Comment by inikep** [comment]
Snappy doesn't work because of _POSIX_C_SOURCE.
For libdeflate there is a collision of heapsort() and heapsort() from <stdlib.h>

**Comment by ebiggers** [comment]
I am just going to rename `heapsort()` to `heap_sort()` in libdeflate so people don't run into this problem anymore.  However, the proper solution is to compile the source code with `-D_ANSI_SOURCE`.

**Comment by inikep** [comment]
For example with `lzbench` it requires adding `-D_ANSI_SOURCE` for `*.c` (too many additional flags) or a separate compilation of deflate_compress.c (Makefile is already huge).
I think `heap_sort()` will be more portable.

**Comment by jibsen** [comment]
Great, thanks @ebiggers.

**Pull request merged**
