### PR TITLE
fixed typo in helptext for -e#

### LINKED ISSUE #55: Typo in help for -e#

### PR DESCRIPTION
**Pull request by DerMolly**
fixes #55

### CODE REVIEW

**Comment by DerUser** [comment]
The linux clang test seems to be brocken:

Many errors in  `lzham`
```fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Makefile:284: recipe for target 'lzham/lzham_assert.o' failed
make: *** [lzham/lzham_assert.o] Error 1
The command "make CC=$CC_COMPILER CXX=$CXX_COMPILER $MORE_OPTIONS" exited with 2
```

no `lzbench` file
```
0.02s$ file ./lzbench
./lzbench: cannot open `./lzbench' (No such file or directory)
The command "file ./lzbench" exited with 0.
```

no runing the `lzbench` file
```
0.00s$ $QEMU_INTERPRETER ./lzbench
/home/travis/.travis/functions: line 104: ./lzbench: No such file or directory
The command "$QEMU_INTERPRETER ./lzbench" exited with 127.
0.00s$ $QEMU_INTERPRETER ./lzbench -eall ./lzbench
/home/travis/.travis/functions: line 104: ./lzbench: No such file or directory
The command "$QEMU_INTERPRETER ./lzbench -eall ./lzbench" exited with 127.
```

**Comment by inikep** [comment]
Thanks fot patch.
Some compressors don't work with newer compilers.
You may use `make DONT_BUILD_LZHAM=1` to disable LZHAM.

**Comment by inikep** [comment]
I fixed all issuses I found with clang up to clang-9:
https://travis-ci.org/inikep/lzbench/builds/601797150

**Comment by tansy** [comment]
I didn't have time to test new release but I found typo, as I guess, in _lzbench/lzbench.cpp  I didn't report yet. In line 721:

`fprintf(stderr, " -e# #=compressors separated by '/' with parameters specified after ',' (deflt=fast)\n");`

should be `(default=fast)`. It has no effect on actual program's work as it's only help displayed but typo nevertheless.

Just discovered [it's been proposed here already](https://github.com/inikep/lzbench/pull/56/commits/3108c23e174b8b067d4f6dfa599b872555c32027) by @DerMolly.

**Pull request closed without merging**
